trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '58dd4450-eb19-4b8e-94e8-ad4089283faf'
  imageRepository: 'josselardinoisdependencycheckapi'
  containerRegistry: 'codecheckregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'
  buildConfiguration: 'Release'

stages:
- stage: BuildAndPushDockerImage
  displayName: Build and push Docker image
  jobs:
  - job: BuildAndPushDockerImage
    displayName: Build and push Docker image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)

- stage: BuildDotNetApp
  displayName: Build and test .NET 6.0 Web API
  jobs:
  - job: BuildDotNetApp
    displayName: Build and test .NET 6.0 Web API
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.0'  # Replace with the actual .NET 6.0 version

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration)'
